name: notification_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.10.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_messaging: ^15.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.2
  cloud_firestore: ^5.4.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
#  freezed: ^2.3.2
#  copy_with_extension_gen: ^5.0.0
  build_runner:
#  json_annotation: ^4.7.0
