name: auth_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.10.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  shared_preferences: ^2.3.2
  get_it: ^8.0.0
  injectable: ^2.5.0


dev_dependencies:
  flutter_lints: ^5.0.0


