name: database_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.10.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  cloud_firestore: ^5.4.4
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^5.0.4
  geoflutterfire_plus: ^0.0.24
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  uuid: ^4.5.1
#  freezed: ^2.3.2
#  copy_with_extension_gen: ^5.0.0
  build_runner:
#  json_annotation: ^4.7.0
