name: storage_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.10.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_storage: ^11.2.5

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
#  freezed: ^2.3.2
#  copy_with_extension_gen: ^5.0.0
  build_runner:
#  json_annotation: ^4.7.0
